#!/bin/bash
# Bradford Smith
# git-rainbow-branches
# 2020-12-27
# Rainbow color output for `git branch -avv`

# shellcheck disable=2034
# this disables the "appears unused" warning from shellcheck because even though
# this script doesn't use the variables git does
USAGE=""
SUBDIRECTORY_OK=true

# shellcheck source=/dev/null
# this is added because shellcheck cannot follow the dynamic path to
# git-sh-setup, this is the way git recommends to do it, so I am ok silencing
# the warning here
source "$(git --exec-path)/git-sh-setup"

require_work_tree

if [ "$1" == "--help" ]; then
    man git-rainbow-branches
    exit
fi

if git config --get-colorbool color.ui; then
    CURRENT_COLOR=$(git config --get-color color.branch.current "green")
    UPSTREAM_COLOR=$(git config --get-color color.branch.upstream "blue")
    RESET=$(git config --get-color "" "reset")

    branches=$(git branch -avv)
    while read -r line; do
        if [[ $line == "* "* ]]; then
            # current branch
            line=$(echo "$line" | sed -e "s/^\* \([[:alnum:]]*\)/* ${CURRENT_COLOR}\1${RESET}/")
        fi
        if [[ $line == *"["* ]] && [[ $line == *"]"* ]]; then
            # upstream branch
            line=$(echo "$line" | sed -e "s/\[\([[:alnum:]]*\/[[:alnum:]]*\)\]/[${UPSTREAM_COLOR}\1${RESET}]/")
        fi
        if [[ $line == "remotes"* ]]; then
            # remote branch
            line="  $line"
        fi
        printf "%s\n" "$line"
    done <<< "$branches"
else
    git branch -avv
fi
