# Bradford Smith
# Makefile for git-rainbow-branches
# 2021-10-29
################################################################################

PREFIX ?= /usr/local
LICENSEPREFIX ?= "$(PREFIX)/share/licenses"
MANPREFIX ?= "$(PREFIX)/share/man/man1"

PRG = git-rainbow-branches
LICENSE = LICENSE
MAN = man1/git-rainbow-branches.1
RM = rm -f

# include options generated by ./configure script
-include Makefile.in

.PHONY: all clean dry-run install uninstall

all:
	@echo "usage: make install"
	@echo "       make uninstall"
	@echo "       make dry-run"
	@echo "       make clean"

clean:
	$(RM) Makefile.in

dry-run:
	@echo "Running 'make install' would install $(PRG) to $(DESTDIR)$(PREFIX)/bin"
	@echo "        and $(LICENSE) to $(DESTDIR)$(LICENSEPREFIX)/$(PRG)"
	@echo "        and $(MAN) to $(DESTDIR)$(MANPREFIX)"

install:
	install -Dm 0755 $(PRG) -t $(DESTDIR)$(PREFIX)/bin
	install -Dm 0644 $(LICENSE) -t $(DESTDIR)$(LICENSEPREFIX)/$(PRG)
	install -Dm 0644 $(MAN) -t $(DESTDIR)$(MANPREFIX)
	gzip -9nf $(DESTDIR)$(MANPREFIX)/$(PRG).1

uninstall:
	$(RM) $(DESTDIR)$(PREFIX)/bin/$(PRG)
	$(RM) $(DESTDIR)$(MANPREFIX)/$(MAN).gz
